backend:
  name: github
  branch: main
  repo: inclusive-design/financial-inclusion.inclusivedesign.ca
  base_url: https://auth.incd.ca
  commit_messages:
    create: 'chore(cms): create "{{path}}"'
    update: 'chore(cms): update "{{path}}"'
    delete: 'chore(cms): delete "{{path}}"'
    uploadMedia: 'chore(cms): upload "{{path}}"'
    deleteMedia: 'chore(cms): delete "{{path}}"'
media_folder: src/assets/uploads
public_folder: /assets/uploads

i18n:
  locales: [en, fr]
  default_locale: en
  save_all_locales: false

collections:
  - label: Chapters
    label_singular: Chapter
    name: chapter
    icon: article
    i18n:
      structure: multiple_folders
    folder: src/collections/chapters/
    extension: md
    create: true
    sortable_fields:
      fields: [title, order]
      default:
        field: order
        direction: ascending
    fields:
      - label: UUID
        name: uuid
        widget: hidden
        default: "{{uuid}}"
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Short Title
        name: shortTitle
        widget: string
        i18n: true
        required: false
      - label: Show in navigation
        name: nav
        widget: boolean
        i18n: true
      - label: Type
        name: type
        widget: select
        options:
          - { label: Standard, value: standard }
          - { label: Narrative, value: narrative }
        i18n: duplicate
        required: true
      - label: Order
        name: order
        widget: number
        i18n: duplicate
        required: false
      - label: Parent
        name: parent
        widget: relation
        collection: chapter
        value_field: uuid
        search_fields: [title]
        display_fields: [title]
        required: false
      - label: Background Image
        name: backgroundImage
        widget: image
        i18n: duplicate
        required: false
      - label: Introduction
        name: introduction
        widget: markdown
        i18n: true
        buttons:
          [
            bold,
            italic,
            link,
            heading-three,
            heading-four,
            heading-five,
            heading-six,
            quote,
            bulleted-list,
            numbered-list,
          ]
        required: false
      - label: Body
        name: body
        widget: markdown
        i18n: true
        buttons:
          [
            bold,
            italic,
            link,
            heading-three,
            heading-four,
            heading-five,
            heading-six,
            quote,
            bulleted-list,
            numbered-list,
          ]
  - label: Back Matter
    label_singular: Back Matter
    name: back-matter
    icon: article
    i18n:
      structure: multiple_folders
    folder: src/collections/back-matter/
    extension: md
    create: true
    sortable_fields:
      fields: [title, order]
      default:
        field: order
        direction: ascending
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Order
        name: order
        widget: number
        i18n: duplicate
        required: false
      - label: Body
        name: body
        widget: markdown
        i18n: true
        buttons:
          [
            bold,
            italic,
            link,
            heading-three,
            heading-four,
            heading-five,
            heading-six,
            quote,
            bulleted-list,
            numbered-list,
          ]
singletons:
  - label: Contact Information
    name: contact
    file: src/_data/contact.json
    icon: map
    fields:
      - label: Email
        name: email
        widget: string
        type: email
      - label: Phone
        name: phone
        widget: string
      - label: Address
        name: address
        widget: text
  - label: Languages
    name: languages
    file: src/_data/languages.json
    i18n: true
    icon: translate
    fields:
      - label: Languages
        label_singular: Language
        name: languages
        widget: list
        i18n: duplicate
        fields:
          - label: Name
            name: name
            widget: string
            i18n: true
          - label: Code
            name: code
            widget: string
            i18n: duplicate
